### ISSUE TITLE
Not  responsive

### ISSUE THREAD

**Issue by grixxxx** [Fanou59/Card_component#1]
avoid putting fixed-width if you want to achieve responsiveness.

![image](https://user-images.githubusercontent.com/110141187/206862501-642147a9-f0c1-4527-b9ea-5c0a40f863a2.png)

**Comment by Fanou59** [comment]
Thank you.
If weight is Auto it's better but the original width is not respected ?

What is your advice ?

**Comment by Fanou59** [comment]
i've changed with :
- body | width : auto
- container | min-width:600 px

Is it better ?

**Comment by grixxxx** [comment]
> ?

much better! always use min and max to achieve responsiveness.

try to remove the `width:  auto`  in the body because the default width is always `auto`
